sudo: required

language: node_js
node_js:
  - "4.1"

services:
  - docker

before_install:
  - docker pull kenjones/authstore-consul
  - docker pull kenjones/authstore-vault
  - docker pull kenjones/nodejs-mocha
  - docker-compose -f docker-compose-test.yml up -d

script:
  - sleep 30
  - mkdir -p $(pwd)/coverage
  - docker run -it --rm -v $(pwd):/app --link=vault -e "VAULT_HOST=vault" kenjones/nodejs-mocha sh -c 'npm install --quiet && npm run coverage'

addons:
  code_climate:
    repo_token: 9b083d9de876dd53937f28b364a2493b091ebbb867430325922f20280483863

# clean up the running support processes and then report code coverage to CodeClimate
after_script:
  - docker-compose -f docker-compose-test.yml stop
  - docker-compose -f docker-compose-test.yml rm -f
  - codeclimate-test-reporter < lcov.info






