sudo: required

language: node_js
node_js:
  - "4.1"

services:
  - docker

before_install:
  - docker pull kenjones/authstore-consul
  - docker pull kenjones/authstore-vault
  - docker pull kenjones/nodejs-mocha
  - docker-compose -f docker-compose-test.yml up -d vault

script:
  - mkdir -p $(pwd)/coverage
  - chmod 777 $(pwd)/coverage
  - docker-compose -f docker-compose-test.yml run -e TRAVIS_JOB_ID=$TRAVIS_JOB_ID vaulted

addons:
  code_climate:
    repo_token: a9b083d9de876dd53937f28b364a2493b091ebbb867430325922f20280483863

# clean up the running support processes and then report code coverage to CodeClimate
after_script:
  - docker logs $(docker ps -q -f status=exited)
  - docker rm $(docker ps -q -f status=exited)
  - docker logs consul
  - docker logs vault
  - docker-compose -f docker-compose-test.yml stop
  - docker-compose -f docker-compose-test.yml rm -f

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/174453f843f3dd2daca7
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

